id: 2026-08-acceder-a-la-surveillance-du-bilan-2
template_id: tuto-release
template_version: 1
charte_version: 1
hash_contenu: 9585608d87045cdec6ac26f4802e3e2844c5bd678b3c2768398e669fa30ca856
statut: brouillon
url_publiee: null
cree_le: '2026-08-19'
build_le: '2026-08-19'
retouche_html_le: null
