id: 2026-09-ajouter-un-titre
template_id: tuto-release
template_version: 1
charte_version: 1
hash_contenu: de743ee13a46f4d4a96610280d387b9a143743c2e0fbbce49282c89cfa417501
statut: brouillon
url_publiee: null
cree_le: '2026-09-09'
build_le: '2026-09-09'
retouche_html_le: null
